name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - paths:
      - ''
    - name: fundamentals ~ f01-tour-of-heroes-app
      run: |
        npm install -g @angular/cli
        cd fundamentals/f01-tour-of-heroes-app
        npm ci
        npm npm run lint
        npm run start &
        npm test -- --watch false --browsers ChromeHeadless
        npm run e2e:webdriver
        npm run e2e:cd
      env:
        CI: true
